language: generic

sudo: required

services:
  - docker
print(1)
# dockerfile.dev이기 때문에 '-f' 명령어 사용
before_install:
  - docker build -t smileajw1004/react-test-app -f ./frontend/Dockerfile.dev ./frontend
print(2)
script:
  - docker run -e CI=true dldbwls492/react-test-app npm test

after_succes:
  - docker build -t dldbwls492/docker-frontend ./frontend
  - docker build -t dldbwls492/docker-backend ./backend
  - docker build -t dldbwls492/docker-nginx ./nginx
  # 도커허브 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # 도커 허브에 push 하기
  - docker push dldbwls492/docker-frontend
  - docker push dldbwls492/docker-backend
  - docker push dldbwls492/docker-nginx